[package]
name = "offst-version"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

edition = "2018"

[dependencies]

common = { path = "../common", version = "0.1.0", package = "offst-common" }

log = "0.4"
futures-preview = "0.3.0-alpha.16"

byteorder = "1.1"
