language: rust
env:
  global:
    - PROJECT_NAME: offset
    - RUST_BACKTRACE: full

git:
  depth: 1

# Don't cache the cargo registry:
# See: https://levans.fr/rust_travis_cache.html
before_cache:
    - ci/post/cargo-sweep.sh
    - rm -rf $HOME/.cargo/registry

cache:
  directories:
    - $HOME/.cargo
    - $HOME/install
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

jobs:
  fast_finish: true
  include:

  - name: Linux
    env: TARGET=x86_64-unknown-linux-gnu
    os: linux
    dist: xenial
    rust: none
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    script:
    - ci/pre/cargo-config.sh
    - ci/pre/capnp.sh
      # Check formatting:
    - cargo fmt --all -- --check
      # Run clippy check:
    - cargo clippy
      # We add target dir so that kcov can find the test files to run:
    - RUSTFLAGS="-C link-dead-code" cargo test --target ${TARGET}
    - ci/post/kcov/try-install.sh
    - ci/post/kcov/run.sh

  - name: macOS
    env: TARGET=x86_64-apple-darwin
    os: osx
    rust: none
    osx_image: xcode9.4.1
    # Solution due to https://travis-ci.community/t/homebrew-syntax-error/5623 :
    before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install capnp
    script:
    - cargo test

  - name: Windows
    env: TARGET=x86_64-pc-windows-msvc
    os: windows
    # Used as a temporary fix for windows CI issue in travis.
    # See: https://travis-ci.community/t/windows-instances-hanging-before-install/250/25
    filter_secrets: false
    rust: none
    before_script:
    # We install vcredist2010 as a requirement for the yasm assembler (Used for ring compilation)
    - choco install vcredist2010 capnproto strawberryperl
    - mkdir -p $HOME/install/yasm
    - curl -o $HOME/install/yasm/yasm.exe https://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
    - export PATH=$HOME/install/yasm:$PATH
    - echo $PATH
    - rustup target add x86_64-pc-windows-msvc
    script:
        - cargo test

    # Based on: https://github.com/kennytm/rust-ios-android/blob/master/.travis.yml
  - name: aarch64-linux-android
    env: TARGET="aarch64-linux-android"
    os: linux
    dist: xenial
    rust: none
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    before_install:
      - source ./ci/android_before_install.sh
    install:
      - ./ci/android_install.sh
    script:
      - cargo build --target ${TARGET}

  - name: armv7-linux-androideabi
    env: TARGET="armv7-linux-androideabi"
    os: linux
    dist: xenial
    rust: none
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    before_install:
      - source ./ci/android_before_install.sh
    install:
      - ./ci/android_install.sh
    script:
      - cargo build --target ${TARGET}

  - name: i686-linux-android
    env: TARGET="i686-linux-android"
    os: linux
    dist: xenial
    rust: none
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    before_install:
      - source ./ci/android_before_install.sh
    install:
      - ./ci/android_install.sh
    script:
      - cargo build --target ${TARGET}


before_deploy: ci/before_deploy.sh
deploy:
  provider: releases
  token:
    secure: MpKcz5y3DQGkZYpekopOAHkErw8RoJSsnLDWzTQg+bxDD4+30Q+aZ21EK6BIvOgNTcGZCpxKAr1iobr9IVv9tlEZVGeV3eiCeAUCq52uQmDfYf5VkckwF5DLBcKN7FLZZVgKq8m30OLXDyxuwogd39LcKzTKyHURQAa7DHSjomUf+Yu+/+PFMxCisvFKl0Etp/qMbPXuoZya19qH5zDNupf4BsB00qJo0SMF8pPZ/p+m+BGotBNNwLWGrfDt5Pv460/0H8MixkrVnt3/tKmZ3MvhQ42bMgMR5vg+j/Ioeiq2jiUjoLaC0HixL8wyOKyiXiuvAE812P5MEeCA6RrjG2q6CaOM+b4+Az5q/PbM5zzmhjT6wWVmNfIb7hqin7k63cAL5BBAmqcWO9LYazk3/8Eqv+/CVGvZyVixz7/qhbBzA/J5sJiu4O5IHYgtchXUcyZh+YIPwQpfwbHhyUl55wIRqMiOohaBxufYBKGUoe5pH26U/acaY4xSzRKCbXTej5bW+pY3OkeUKZFEETDAPdGcGjrD12CFbSaY5ikYmkFSDKluMcbvXpWCRXvPo+D+c1RPJ6xxxYKA/+6AH3nhQEwX6viEYD/XtxPYUEdbgYcImz/HL5clo6j0uiP/gHmrdGY+tg8btOozNvkNXMKJyEffYMFyuDbPrjWOK712/pU=
  file: $HOME/deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  on:
    tags: true
    repo: freedomlayer/offset
    branch: master
branches:
  only:
    # Pushes and PR to the master branch
    - master
    # Ruby regex to match tags. Required, or travis won't trigger deploys when
    # a new tag is pushed. Version tags should be of the form: v0.1.0
    - /^v\d+\.\d+\.\d+.*$/
