language: rust
dist: trusty
sudo: required
cache:
  cargo: true
  directories:
    - $HOME/capnp
    - $HOME/kcov-x86_64-unknown-linux-gnu

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-6 CXX=g++-6 KCOV=1
      os: linux
      rust: nightly-2018-08-02
      before_script:
        - travis/trusty/before-script.sh
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      script:
        - cargo clean && cargo clippy
      after_success:
        - travis/trusty/after-success.sh

    - env: TARGET=x86_64-apple-darwin KCOV=0
      os: osx
      rust: nightly-2018-08-02
      osx_image: xcode9.2
      before_script:
        - brew install capnp
      script:
        - cargo clean && cargo test
