[package]
name = "offst-bin"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
license = "AGPL-3.0"
edition = "2018"

[lib]
name = "bin"
path = "src/lib.rs"

[[bin]]
name = "strelay"
path = "src/bin/strelay.rs"

[[bin]]
name = "stindex"
path = "src/bin/stindex.rs"

[[bin]]
name = "stnode"
path = "src/bin/stnode.rs"

[[bin]]
# OffST ManaGeR
name = "stmgr"
path = "src/bin/stmgr.rs"

[dependencies]

common = { path = "../common", version = "0.1.0", package = "offst-common" }
crypto = { path = "../crypto", version = "0.1.0", package = "offst-crypto" }
identity = { path = "../identity", version = "0.1.0" , package = "offst-identity" }
timer = { path = "../timer", version = "0.1.0" , package = "offst-timer" }
proto = { path = "../proto", version = "0.1.0" , package = "offst-proto" }
relay = { path = "../relay", version = "0.1.0" , package = "offst-relay" }
net = { path = "../net", version = "0.1.0" , package = "offst-net" }
index_server = { path = "../index_server", version = "0.1.0" , package = "offst-index-server" }
node = { path = "../node", version = "0.1.0" , package = "offst-node" }
keepalive = { path = "../keepalive", version = "0.1.0" , package = "offst-keepalive" }
version = { path = "../version", version = "0.1.0" , package = "offst-version" }
secure_channel = { path = "../secure_channel", version = "0.1.0" , package = "offst-secure-channel" }
database = { path = "../database", version = "0.1.0" , package = "offst-database" }
connection = { path = "../connection", version = "0.1.0" , package = "offst-connection" }

toml = "0.4.10"
serde = {version = "1.0.87", features = ["derive"]}
base64 = "0.10.1"

log = "0.4"
env_logger = "0.6.0"
futures = {version = "0.3.1", features = ["thread-pool"]}
async-std = "1.2.0"

structopt = "0.2.15"

derive_more = "0.99.2"

[dev-dependencies]

tempfile = "3.0.5"
